wallpaper {
    monitor = DP-1
    path = /home/hayden/Dots/wallpapers/mountains.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/hayden/Dots/wallpapers/mountains.jpg
    fit_mode = cover
}

splash = false
